[package]
name = "skvm"
version = "0.1.0"
authors = ["scc <66scc66@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
getrandom = { version = "0.2.8", features = ["js"] }
chrono = { version = "0.4.26", default-features = false, features = ["clock", "std", "wasmbind"] }
boa_engine = { path = "./skboa/boa_engine" }
wasm-bindgen-test = "0.3.13"
js-sys = "0.3.61"
protobuf = "3.2.0"
cid = '0.10'

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
