name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.CC_GA }} # ----- BEGIN RSA PRIVATE KEY----- ...
      - run: ssh -T git@github.com || true
      - run: git submodule update --init --recursive
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm run --if-present lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.CC_GA }} # ----- BEGIN RSA PRIVATE KEY----- ...
      - run: ssh -T git@github.com || true
      - run: git submodule update --init --recursive
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: build packages
        run: pnpm run -r build

      - name: test
        run: pnpm run test
